---
title: "First-year in Second/Third-year Class"
date: 2026-04-17
wordcount: 391
categories: [school]
---

One of the most common questions I get in class is: why are you here? 

It's a good question, considering it does seem bizarre how a first-year is taking a class primarily composed of second or third-year students. Usually, my answer depends on how much I feel like explaining. The short version is dual enrollment. That also explains my senior standing.

Even so, I feel out of place.

As a first-year microbiology major, I’m taking general microbiology with other micro majors who have been in college longer than I have. Most of the time, I don’t notice the difference. That is, until the conversation shifts. They talk about bar crawls, internships, and things that feel out of reach for me. 

And then there’s studying. They seem to know how to do it. They know how to prepare for exams, how to manage their time, or how to get into research. It’s difficult to say if I even figured out what I should do. It took me until this third quarter just to start settling in.

It’s not just a social change, but it’s also a huge shift in academics. In high school and community college, I got away with barely studying. I would do some homework, a few practice problems, maybe pay attention in class, and that was enough. University isn’t as forgiving. Exams demand critical thinking and labs carry significant weight. It’s easy to get Bs but the gap between As and Bs feels much wider.

I also wouldn’t call myself a studious person. I enjoy learning, but I struggle staying focused in class and working through material methodically. 

Despite all of this, being ahead in the curriculum has its benefits. The main one: pestering my upperclassmen with questions. After getting over the initial hesitation, it’s become something I enjoy.

Through them, I learned so much about research, my major, possible career paths, and which classes are worth taking. More than that, I’ve started to enjoy asking questions.

I’ve never been someone who asks questions easily. I’ve always had them, but saying them out loud used to feel awkward. I’m not sure what changed, but somewhere along the way, I started asking and it made everything a little clearer. 

That’s the thing, isn’t it? I’m not learning at the same pace as everyone else. I’m learning how to ask questions.
