---
title: "Girlnough"
date: 2026-01-19
categories: [poem]
---
:::{.poem}

I could wake up in the morning,  
Wash my face and slap on lotion,  
Patiently wait for it to dry,  
While folding my cleaned laundry.  

I could clip my hair with cute pins,  
Sharpen my eyebrows with tweezers,  
Trim my bangs just below my eyes,  
Curl my hair into bouncy Js.  

I could look almost effortless,  
Use concealer as foundation,  
Cherry pink under my eyebags,  
Add eyeshadow as eyeliner.  

I could wear off the shoulder tops,  
Paired with high-waisted baggy jeans,  
Chunky sneakers to finish it,  
Now I almost look like a girl.  

I could smile if they glance at me,  
Ask them questions about their day,  
Be interested in their life,  
I almost blend in with the girls.  

I suppose I could do much more,  
In fact, I can’t help but compare,  
How they are well groomed and pretty,  
So why don’t I feel pretty too?  

Their beauty and my beauty clash,  
Different aesthetics and preference,  
I’m trying to play on their home field,  
It’s no wonder I feel awkward.  

Maybe I don’t need to blend in,  
Or find out what is wrong with me.  
I don’t need their type of pretty,  
I want mine to make me alive.  
:::